#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-2 --mode 1920x1080 --rate 144.00 &
picom --detect-rounded-corners &
feh --bg-fill --no-fehbg ~/Pictures/wallpapers/0327_wolfgang.png &
xset s off -dpms &
setxkbmap -option caps:escape &

# Workspaces #
bspc monitor DP-2 -d I II III IV V 

# Extra config stuff #
bspc config border_width         4
# bspc config border_radius        6
bspc config window_gap          28
bspc config split_ratio          0.6
bspc config focus_follows_pointer true

# Colors #
bspc config normal_border_color "#928374" 
bspc config focused_border_color "#79740e"
bspc config presel_feedback_color "#b57614" 

# Rules #
bspc rule -a firefox desktop="^1" follow=on
bspc rule -a discord desktop="^2" follow=on
bspc rule -a Steam desktop="^3" follow=on
bspc rule -a Brawlhalla desktop="^3" follow=on
bspc rule -a lunarclient desktop="^5" follow=on


$HOME/.config/polybar/launch.sh
